### PR TITLE
Uncrappify the UI

### PR DESCRIPTION
**Pull request by scunz**
Great approach to get the Heaven **CentralUi** classes in a usable shape. _Usable shape_ refers to the code base here. There will be follow ups that deal with the visual appearance.

Tasks:
- [x] Actually use the concept of 'Modes' to switch between _Welcome_ and what we still call _Novice_.
- [x] Read layout definitions into the `WindowStateBase` class and its derivats - instead of UserLevel-Configuration that used to dwell in libMacGitverCore.
- [x] Remove all view creation from libMacGitverCore and teaches libHeaven to synchronize a WindowStateBase hierarchy with the current layout.
- [x] Don't regenerate the user interface when switching the active repository.
- [x] Get rid of the multiple inheritance used in View/Container classes.
- [x] Fix layouting Widgets / Toolbars inside of Views.
- [x] WindowStates: Provide a Key/Value container that can persist individual views' settings. (Based on a `QSharedDataPointer`, so that is versatile usable, which is the main drawback of the current (unfinished for that reason) implementation on `QDomElement`.
- [ ] WindowStates: Get rid of `QDomDocument`s as settings containers.
- [ ] WindowStates: Synchronize closing of view with window state
- [ ] WindowStates: Persist and restore view-local state information.
- [ ] Provide a TreeView that will put it's visual state into a model (A state model, not an Item Model). It's weird that a tree looses the item-is-expanded state when we switch between repositories.
- [x] Implement Contexts
- [x] **MacGitverModules**: port RepoTreeView to ViewContexts
- [ ] **MacGitverModules**: port Branches to ViewContexts
- [ ] **MacGitverModules**: port HistoryView to ViewContexts
- [ ] **MacGitverModules**: port WorkTree to ViewContexts
- [ ] **MacGitverModules**: port Refs to ViewContexts
- [ ] **MacGitverModules**: port Tags to ViewContexts
- [x] make libHeaven's ContextManager a cache for such contexts.
- [x] correct destruction of `ViewContextData` and co
- [x] on switching active repository, detach all contextual views from their contexts, switch and reattach to new or cached contexts.
- [x] make `ViewFactory` internal and manage all the data (that MGV-Main/Core have locally) directly inside libHeaven, so we can implement features like "Add View" (We're missing a title for the view currently, as we only got the identifier down in libHeaven).
- [x] Lots more of documentation
- [ ] Update remaining copyrights to assign primary copyright to the devs-group, but include individual copyrights.
- [x] Final code style update: Move all remaining .h files to .hpp
- [ ] Fix crashes on ending the application build with Qt5.

### CODE REVIEW

**Comment by scunz** [comment]
@antis81, given the complexity of this topic, i barely dare to ask for a review on these changes. However, could you have a short look across the "uncrappify1" branches if I did something fundamentally wrong?

**Comment by antis81** [comment]
Yes, I'll review - just give me some days. I'm really excited for these changes as coding the views is not really pleasant at present. I also have some more nice changes to finally make use of Git::Index in the queue. Just thaught it is too unfinished to ship it yet - :sailboat:.

**Comment by scunz** [comment]
Correct. I meanwhile found out, that the problem in history view that I was observing... Well, it was just a silly mistake.

btw: I recently realized: libHeaven is the biggest part of MacGitver, almost 50% of the total code... :-)

**Comment by scunz** [comment]
So, I fixed the history view (directly in development branch) and got my automatic-switching toolbars back.

Meaning: The code of this whole change set does now (visually) exactly the same as the old code did (With one exception: When switching repositories the UI is no longer reset).

Should we get this in _now_ or should I all stuff upon this into this branch?

**Comment by antis81** [comment]
On a first quick look, the whole thing looks very clean to me. There's something I'm still missing - "Dockable Views". Maybe this should be an additional attribute/flag, as it is not really a type or subtype.

For the fix, I tend to keep it in the `uncrappify1` branch. If you put it in `development` it disturbs your workflow a little. But I'm fine with either way you chose. For the `IndexView` branch I plan to merge you changes over from development, after you are finished. Meanwhile, I would go on implementing the Git::Index functionality and the Diff-Hunk-Selection view.

**Comment by scunz** [comment]
> There's something I'm still missing - "Dockable Views".

If the code is really as good as I believe it to be, only the showing of `SecondaryWindow` should be required to configure a _mode_ with an undocked view inside. However, I really started to prefer a one-by-one strategy wrt. new features :-)

> For the fix, I tend to keep it in the `uncrappify1` branch. If you put it in `development` it disturbs your workflow a little. But I'm fine with either way you chose.

really? I would be surprised if that finally turns out to be better, but I think that I will give it a try.

**Comment by scunz** [comment]
Yeah, @antis81, for `libHeaven`, Jenkins comments again on the compilabilty of Pull-Requests :-)

**Comment by antis81** [comment]
Cool :+1:.

**Comment by scunz** [comment]
So this one is getting large.

I managed to get totally rid of the multiple inheritance used in ViewContainers. Now I'm about to get those context things sorted out. As it currently looks with these contexts mgv-core wont need any special handling for selections. It can almost all be done down in libHeaven.

**Comment by scunz** [comment]
I think, you recently requested a Screen-Shot of what's going on; so here's a short intermediate summary:
snapshot1
(This is from the code that I _just now_ pushed into the uncrappify branches)
- Modes are now named "(level)#(modename)" (See the widget in the right upper corner, which itself is probably to scared of its own ugliness to show up on a macintosh)
- Really just by accident, I think i fixed the ignorance of sizeHint() et al. on derivats of `View`. As a result, the left views start now with a nice width.
- All views now learned to handle a central widget and a tool bar. I've changed all views to operate like this. As a consequence, the tool bar of the Branches View is now integrated into the `MultiBar` (the one in the left middle which contains the 'x')
- I've converted the Branches View to use a `QAbstractItemModel` arranged as a tree; instead of a flat list. It used to work, but I think my last warning-reduction introduced an error (as you might see in the screenshot: origin/topic/uncrappify1 is at the wrong position).
- But the main point is probably: It looks mostly the same, even though I think i did a total rewrite of the underlying libHeaven code...

**Comment by scunz** [comment]
Fixed the above bespoken error in `MacGitverModules` :-)

**Comment by antis81** [comment]
Yeah, very good thing :smile:. I've also build it on osx and the only error I got was a linker error caused by the missing implmentation of a slot. I outcommented it temporary and voila - same view like yours ( with different coloring :smile: ). I like the RefsView.

Some (minor) notes: On mac, the "disabled button text" is very hard to read.The color of the "commit description" seems to be the selection color, which I think is not intended.

**Comment by scunz** [comment]
Yeah, there are still so much of such _small_ mistakes... focus color in history, details not scrollable, linenumbers in diff are few pixels too small (rendered correctly, but calculated differently for drawing), ....

Could go on like this for just a while :-)

**Comment by scunz** [comment]
Oh, and the build error should have been fixed last night... Cant rembember if i pushed that one, though. Definitely need a tool to figure out, which submodule need attention. Command line git gets really boring when it comes to SMs...

**Comment by scunz** [comment]
@antis81, along with the deleting of `ViewContextData` objects from my last commit, I _think_ that ViewContexts are now fully implemented. I currently don't see any missing functionality. Few documentation items are still missing and a general overview. Hope these will follow soon.

**Comment by scunz** [comment]
It's incredibile how damn slow this Windows-Thingie is... The rebase action on the 4 submodules with a topic/uncrappify branch, just took me approximately 25 minutes. On Linux or Mac this operation would have been done in 2 minutes.

**Comment by scunz** [comment]
@antis81,

what do you think about the progress of this PR?
RepoTreeView and Branches are more or less ported to the changes and the View/Context changes themselves are complete. WindowState are complete to the point they were before and implement new features beyond that.
Documentation has improved _very much_ but isn't finished yet. What's missing still is the `ContextKeys` class and some stuff that the remaining features will still change.

This whole thing is getting too big to handle. I'd like to merge it and move the remaining tasks (which are actually more new features) to other issues.

**Comment by antis81** [comment]
Yeah, I think it's good to merge here and do the rest of the docs at a later point. Also, porting the views is dependent on that one - so it is a good thing to bring the changes in before.

**Comment by scunz** [comment]
Okay, so i will prepare it for merge tonight and hopefully get it in before dawn :-)

**Comment by scunz** [comment]
Jenkins was sooo shocked by this big bummer, that it took almost 6 minutes to update its refs.... But since then operation is as usual again. :-)

**Pull request merged**
