### PR TITLE
Feature: Advanced DynamicActionMergers

### PR DESCRIPTION
**Pull request by scunz**
Up to now, the dynamic action merger interface is only able to call back to the consumer code when the internal menu structure has to be rebuild.
This patchset adds another mode to the DAM interface, so that it is possible to register actions with the DAM or simple set a list with mappings from "Display" to "Variant", from which the DAM will internally create `QAction` objects and handle their triggering; resulting in a single emitted signal that has the Variant as parameter.

### CODE REVIEW

**Comment by scunz** [comment]
I'm still holding this back, since the documentation is still in the pipeline.

**Comment by scunz** [comment]
From my PoV, this is now ready to merge. It includes full doxygen documentation for the public part of the `DynamicActionMerger` class.

@antis81, any objections against a merge?

**Comment by antis81** [comment]
Just cross read it and this one looks pretty good. So, just merge it whenever you are ready.

I'm not sure though, if we need that "much" docs. But we'll see later.

**Comment by scunz** [comment]
Documentation is kinda binary. Either it is good and thus of  some use; or it isn't - in which case it is a pure waste of time.

**Pull request merged**
