### PR TITLE
Purifiy all the skies in heaven :)

### PR DESCRIPTION
**Pull request by scunz**

### CODE REVIEW

**Comment by scunz** [comment]
@antis81 does this make any sense so far? :-)

**Comment by scunz** [comment]
Adjustments to this shiny tiny change are tracked in `sc/a/purifiedskies`...

**Comment by scunz** [comment]
Oh and, just by the way, while finally implementing something useful for our "modes", this introduces a slightly new user interaction concept. Gonna write about that soonish...

**Comment by scunz** [comment]
mgv_bluesky

@antis81 Just a first impression. Still lots of work to do here...

**Comment by antis81** [comment]
Woooow .... Great style ... Looking Great :100: :+1: Forwarding to @claus007 :smile:.

**Comment by scunz** [comment]
Actually, it is still the old fox, just with a new dress; But a little closer to QtCreator :)

**Comment by scunz** [comment]
This is from the new heaven tester, which i actually used to implement this:

skytest

**Comment by scunz** [comment]
Damn it. I was writing a length comment here yesterday and it just vanished...

@antis81 Basically, I have a problem with the style(s). In order to solve it, I want to change MGV to **not use the OS style** for the `PrimaryWindow` and `SecondaryWindow` objects. But this has some implications that I want to discuss first.

But first things first: Why is it necessary at all? I recently had the chance to dig deeply into all of Qt's QStyle classes. As a result I have a just refreshed knowledge of how they internally work. Mac OS X style is mostly implemented in Objective C and uses mostly UIKit, CoreUI and Carbon frameworks for display and/or getting settings. It runs of course only on Mac OS X. `QWindowsStyle` is a Qt based style that runs everywhere. It looks like a 19-90ies Windows... `QWindowsXPStyle` is implemented on top of that and uses some OS functions for getting settings and for some drawing too. `QWindowsVistaStyle` (The current one) is based on the XP-Style and does heavy use of Active X and other Windows based functionality. So, these 2 will only run on Windows.

That means, I am only able to test the "really native qt" styles: `QWindowsStyle`, `QPlastiqueStyle`, `QCleanlooksStyle` and the `QFusionStyle`. The latter is only supplied with Qt5. Of course, I can also test with the native KDE Style (Oxygen). But I feel like this is a threat for my eyes :)

So, I cannot test the effect of my changes - and we still got the problems with ToolBars looking ugly everywhere and some other stuff like scrollbars and tree views. I want to get rid of that issues, but don't really know how I can do it (without switching to that platforms and test there, switch back to see if I did not break anything and so on... and I have no Mac available here).

The only solution that I currently see, is: Use a unique style as base. I am trending towards the QFusionStyle, because it would solve the scrollbar problem out of the box (QFusionStyle scrollbars have squared edges and fit nicely to the rest of heaven).

But we probably want dialog boxes to be displayed with the native style (I am not talking about Mac Sheets here; these should be native anyway). So, the change I want to do is:
1. Unconditionally use `QFusionStyle` as base for `BlueSky::Style`
2. That probably means, import the `QFusionStyle` code and compile it if we're building against Qt4
3. Make all MGV Dialogs inherit `Heaven::Dialog` instead of `QDialog` (Dialog is the last used class in libHeaven, will move it to libBlueSky for that purpose)
4. Add a `Heaven::Dialog` based `QMessageBox` class, if we want to use that.
5. During boot, save the `QApplication::style()` somewhere in BlueSky. Then set `BlueSky::Style` as application style.

This would also let us get rid of some costly calculations in the style to find out of a widget is styled or not...

What do you think about this?

**Comment by scunz** [comment]
An how it looks on Windows:
mgv_win

**Comment by scunz** [comment]
> But we probably want dialog boxes to be displayed with the native style.

This simply doesn't work. I know that I have done that before, but whatever I try, it doesn't want to work in MGV.

**Comment by scunz** [comment]
Never mind. The watch :dog: solves this, too...

**Comment by antis81** [comment]
@scunz As for the style concept: :+1: I'm looking forward to that. Qt5.2 should be available soon and from then on we don't need to compile against Qt4 anymore, right? At least that's what I'm hoping for. If you didn't read yet, look into a somewhat older Qt blog about the Fusion style: http://blog.qt.digia.com/blog/2012/10/30/cleaning-up-styles-in-qt5-and-adding-fusion

If I understand you right, it is still possible to switch to native styles. Nothing against that.

Concerning the Heaven::Dialog idea: Great! And if we can use the sheets mechanism on mac ... even greater :smile:.

**Comment by scunz** [comment]
@antis81 

Nice to hear that this is the right direction. We can actually use Qt5 without any bigger problems right now. I don't see any reason not to - as where ever I use it, it works just nice.

But we should note, that compiling Qt5 on Windows is, well, a PITA would still be an understatement. Compiling Qt5 on Windows requires to
- Install: Ruby, Perl, Python
- Compile: Icu, zlib, openssl.

That is a fair amount of work and hard to get it right.

For the switching: Using the internal `Dialog::WatchDog`, it is now possible to have an application using style `X` while `BlueSky::Dialog` uses style `Y`.

The `BlueSky::Style` is still a "proxy style", meaning it just "amends" another style. So, basically it is possible to change the underlying style (I currently set it fixed to CleanLooks). But exactly that ability is what caused the problem in the first place.

**Comment by scunz** [comment]
So... This PR and its associates removes the concept of "User Levels". Even though, this was a fundamental idea behind creating MacGitver, I think that we really don't need it. We can provide a so intuitive user interface that we don't need to care if there's a guru or a first timer before the keyboard...

**Comment by scunz** [comment]
Still remember the 
skytest_wisdom

**Comment by scunz** [comment]
... old "MS Office" wizzards :)

**Comment by scunz** [comment]
But again, more serious:
mgv_qt5
This is the current MacGitver on a Qt5 based build with fusion as style to proxy the BlueSky::Style into.

First of all, this surely shows some flaws of the Diff View as we have them currently.

Note, that the Fusion scrollbars don't leave wired gaps anywhere in the corners.

Having a look at the "History" and "WorkingTree" tabs at the top, this shows a nasty effect. These things are a QPainterPath filled with a vertical linear gradient. On Qt4, just "filling" the path is ugly. Drawing the path upon the filled, makes it look somewhat good, but bordered. On Qt5, filling the path is okay. Drawing the same path upon it, looks like child's draw again. Sigh. Not sure what to do about that, somehow.

**Comment by scunz** [comment]
Hmm, there are serious flaws with mode switching, but I actually didn't touch the ModeSwitcher (contentwise)... So looks like it's gonna be a week of debugging, now :)

**Comment by scunz** [comment]
@antis81 I'm sorry to delay this so much. But I don't find where the flaw is. I really want all of this change set merged.

But the data structures are too complex (for finding it by just looking at the code) and I don't seem to get the right debugging tool set up to dig for this...

**Comment by scunz** [comment]
@antis81 So, I wrote the `libStairway`, which is a nice debugging tool - but far from working correctly.
I'm tempted to fix the flaws and turn it into a standalone debugger with remoting capabilities (Would be the 3rd time that I write such a tool, but this time on my own copyright ^^).

This helps mostly in 2 situations:
1. Like here: Add the ability to see the widget hierarchy in live time in a separate window.
2. Smart pointer debugging: Adds the ability to track what happens to the reference counting of smart pointers. I know that my intuition is fairly good when it comes to choosing the right mechanisms in software development, but I wouldn't trust that I'm always right. MGV makes heavy use of smart pointers and I never actually tested for leaks...

Basically, this works something like: Filtering events (like smart pointer object creation, deletion, refcount increment/decrement, widget reparenting, adding/removing children) in the main thread and queue them up. In a worker thread, wake up every now and then and take the queue off of the main thread. Then flush it to disc and optionally over a socket to a server. The server on the other side can get the data either from a logged session or live via the network. It then shows any currently alive objects and their data.

Using the stairway lib, I found the first fix ("Don't delete containers during mode switch" above), which was a serious bug and actually present since I implemented the container self deleting.

But having fixed that, mode switching still doesn't show anything sometimes and simply swallows some widgets at other times. I was not able to find a logic in that; I cannot even reliably reproduce it. I kept on reading the code over and over again and looked at the stairway output - but actually, nothing obvious showed up.

Finally, I realized that everything indeed is right; but just not shown. Then, off screen, I figured out that there is a problem in setting things back into "visible" state after they have been stashed away for later usage. Actually, I only got a rough idea about why this is happening, but turning the reusing of existing containers and views off, makes it suddenly work.
I'll keep that as a work around and continue to do some of the things that I wanted to do in this PR in the first place...

**Pull request merged**
