### PR TITLE
Hierarchy Debugger

### PR DESCRIPTION
**Pull request by scunz**
Simplistic change set to libHeaven that allows one to press F10 and get a detailed report of the widget/layout hierarchy onto the `qDebug()` stream...

### CODE REVIEW

**Comment by scunz** [comment]
@antis81 
Using this kind of tooling, I can now actually a) prove that the minSize() is in charge and b) narrow it down to some strange thing.

Please merge this code locally and try it yourself. You'll see that inside `QStackedLayout` the combined `minimumSizeHint()` of `HistoryView` and `IndexWidget` suddenly become a mandatory `minimumSize()` of the layout, and thus propagate up the hierarchy to the root window.

The strange thing now is: Looking at `QStackedLayout`'s code tells a different tale: What is written there (esp. in `QStackedLayout::minimumSize()`) seems to be pretty straight forward.

As I've at least localised where this bug comes from, I can see that it will have an effect on my other projects, too. So, I'm very interested in getting this sorted out. But I'm not sure what the next step would be.

**Comment by antis81** [comment]
@scunz No need to merge - just checked it out. With your test code I can also prove this. On my old MacBook, the main window is exactly resized to `1406x841 px`.

I went a little farther and boiled it down to just the `HistoryView`. First, I removed the `HistoryModule` completely and after that, even in the `IndexModule` everything fits just fine. So everything comes down to the initialization code of `HistoryView`. As soon as the history list alone gets visible, it "suddenly" gets a `minimumSizeHint` of `1056x792` through `BlueSky::MiniSplitter`. But when I output the `minimumSizeHint` of the history widget itself, it is just something like `68x98`.

I also couldn't find any hint on where these strange sizes get set or something. Also fiddled a bit with the size policies - no change at all. I think to really track it down to the bone :skull:, we have to go and find all place(s), where the minimum size is calculated :walking:. Phew, this is a long and winding rocky road ... But the good news is: When this is done, we can "release anytime" :smile:.

**Comment by scunz** [comment]
> I went a little farther and boiled it down to just the `HistoryView`.

Sadly, the conclusion that you're drawing out of this is wrong. I saw `IndexModule` behaving the same. Also, note that the problem is probably inside `qSmartMinSize`... Also: With XWorkbench, where I put not `QStackedWidget` into the layout at all, it doesn't happen at all.

**Comment by antis81** [comment]
Would you believe me, if I tell you we can "fix" this by changing a single line in libBlueSky? Remove this line and be blown away:
https://github.com/macgitver/libHeaven/blob/development/libBlueSky/Windows.cpp#L97

:smile::smile::smile:

(it's just the footer that becomes a little "too high" - but fix is easy).

Concerning the `qSmartMinSize` you're probably right. I just couldn't find anything in Qt's reports so far, leading in this direction.

**Comment by scunz** [comment]
> Would you believe me, if I tell you we can "fix" this by changing a single line in libBlueSky? Remove this line and be blown away.

I almost do believe you. I've been revisiting that line actually a few times. But it is correct - At least that's what I've been always thinking. Maybe we should remove the "Expanding" in vertical direction anyway.

However, thinking about it again: The way I create the PrimaryWindow's `QGridLayout` might be at fault.

**Comment by antis81** [comment]
> I almost do believe you. I've been revisiting that line actually a few times. But it is correct - At least that's what I've been always thinking. Maybe we should remove the "Expanding" in vertical direction anyway.

The `MinimumExpanding` here is actually wrong. It means the main window cannot shrink beyond `sizeHint`, which is a) accumulated of the childs sizeHints and b) not the minimum size possible. The default is `Preferred` (or maybe `Expanding` for QMainWindow, not sure). Let's keep it that way.

**Comment by antis81** [comment]
The possible minimum size of the main window becomes this:
mgv_minsize

**Comment by scunz** [comment]
The small size isn't looking good, but it is what can be reasonably expected. I'd say: job well done.

**Comment by antis81** [comment]
This is exactly what I wanted to say with this :+1:. When going to Welcome mode, we can even put it as a mark on an envelope and send it to the alps ... :smile: 
mgv_in_alps

Btw.: Splitters and everything is still completely intact. This is all not about a real scenario, just a not restraining feature to heavenly apps :).

Case closed?

**Comment by scunz** [comment]
> Case closed?

Yeah, let's put this file to rest :)

**Pull request closed without merging**
