### PR TITLE
added keyboard shortcuts

### PR DESCRIPTION
**Pull request by antis81**
The implementation uses `QKeySequence::fromString()` to resolve a string like `Ctrl+O`to the correct key sequence. The HIC will transform to either `trUtf8("shortcut")` or `QLatin1String("shortcut")` depending on using quotation marks in the hid file.

### CODE REVIEW

**Comment by scunz** [comment]
I'll writeup something for the enum and attach it _here_.

**Comment by antis81** [comment]
Yeah cool! Btw.: White spaces (e.g. in a property value) are giving HIC hiccups :smile:. Maybe we could treat them like normal characters and focus on brackets, semicolon and so on. Currently the HIC parser thinks, that a new token starts and errors out here.

**Comment by scunz** [comment]
Ah, good, you're reminding me of that... :-) I didn't think about that when I reviewed your changes so far.

Actually, if a property value contains spaces or tabs, I _think_ it should be defined as `HICP_TRString`. i.e. we want Shortcut always be routed through tr(). But I'm not sure on the translation context of that. Will have to think about that one again.
OTOH: We don't want to shovel icon names through TR (and certainly should demand no spaces inside their names either). But IF we do allow spaces inside them, it might be easier to treat single-quoted text as `HICP_String`...

As for the enum-changes. I'm already there, just takes a few minutes more before i can push :-)

**Comment by scunz** [comment]
Here we go... Took a "few" lines of code more than I initially thought...

**Comment by scunz** [comment]
And examples are never bad... ^^

**Comment by antis81** [comment]
Segfault ... on the enum? About to push back.

**Comment by scunz** [comment]
It shouldn't segfault, but it's not super-safe either.

**Comment by antis81** [comment]
Ok, works so far. Maybe later on we could use something more elegant similar to the Q_ENUMS macro?

**Comment by scunz** [comment]
We could indeed import all Q_ENUM metadata into the hic. But I doubt that this work is worth it.

I'm still undecided about a way to make MacGitver scriptable, later. I was thinking about different ways:
- Link against PyQt and allow to execute Python scripts from within mgv. This would require us to write Python bindings to libHeaven and libGitWrap - The benefit would be that complete MGV-Modules could be written in Python. 
- Use ECMA script. Again we'd have to write bindings to gitwrap and heaven - but that should be easier, since it could be QScript based.
- Invent an own language (I'm thinking of something like "Basic"), base an IDE upon libHeaven. This would be a charming approach, since it would lay the foundation for a nice new type of project, which - since 10 years - i want to start some day: Create a _working, free and Cross-Platform clone of Microsoft Accesss_ I've never been satisfied with the alternatives in that realm... However, what i initially wanted to say: This would seem like a good place where the Q_ENUM extraction from meta data could be leveraged.
- qml. I'm still not at all happy about that development...

**Comment by scunz** [comment]
That being said, I don't see any reason to delay this PR - unless you want to make more of `QAction`-API available to `Heaven::Action` and hic within this PR. Feel free to merge it in.

**Comment by antis81** [comment]
First, I don't want to delay the PR either and am just happy, that you reviewed it and helped so far. So we can move on to the next important steps.

Phew, this is a lot of new ideas. In short to the scripting approach.
- BASIC :-1: (hate this language with a passion :smile_cat:) - MSAccess is dead and LibreOffice has an almost complete clone with access to any database btw.?
- PyQt :+1: -> have a look here: http://qt-project.org/wiki/Category:LanguageBindings::PySide
- QScript :+1: (it's JavaScript as far as I know)
- Own language ... naaaa, you don't really want that.
- QML -> I do not know it well, but I think it's made for touch screens instead of full fledged serious desktop apps.

All in all this is deserves separate issue(s).

**Comment by scunz** [comment]
Well, there is a very big germany-based company that produces ERP/CRM-Solutions and all kind of bussiness applications around that. As it happens, this company has an offspring, whose headquarters reside in the very same building as the ERP-Company somewhere in the south, not too far away from Microsoft Germany headquarters.... However, that offspring once hired me to improve their MS Access based inhouse developed software for managing customer relationships (from phone-contact to the actual billing).

I still guess that says something about the usefullness of MS Access.

I don't like it either, but I still know of no other software that lets you setup a small database solution with a small amount of time and work. OpenOffice / LibreOffice seems to me to be a joke in that respect. ooo/loo is a good thing; but not at databases.

As for basic: I learned it at the age of 8. I could barely read and didn't understand a bit about English. I'm almost 34 now and I must admit that 10 years have passed since the last time I really used basic for something. But if I were to design a language that a non-developer or a beginner could use, it would for sure share some ideas from basic.

As for the other topics, you're right, I'm going to open a discussion-issue on the mgv repo for that.

**Comment by scunz** [comment]
@antis81

> Btw.: White spaces (e.g. in a property value) are giving HIC hiccups :smile:.

This is solved in https://github.com/macgitver/libHeaven/commit/9aa9e0b0fc2a205993828e03d4256325a6b4b376

**Comment by antis81** [comment]
I've noticed that already. Cool. Merry christmas then. I'll be off the next few days to celebrate. Cu next year :smile:

**Pull request merged**
